name: Check Code Style

on:
  push:
  pull_request:

jobs:
  check_code_style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Format code
        run: |
          find ./ -iname *.cs -o | xargs clang-format -i --style=Google --verbose

      - name: Compare to the original code
        run: |
          git diff HEAD --exit-code